FROM debian:latest

RUN apt-get update && apt-get install -y tcpdump libcap2-bin

RUN mkdir -p /home/tcpdump/captures

COPY --chmod=0777 entrypoint.sh /entrypoint.sh

RUN setcap cap_net_raw,cap_net_admin=eip /usr/bin/tcpdump

USER tcpdump

ENTRYPOINT [ "/entrypoint.sh" ]